#!/usr/bin/env bash
# Initialize all dependencies and validate the repository harness.
set -e

HARNESS_ROOT="$(cd -P "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
PROJECT_ROOT="$(cd "$HARNESS_ROOT/.." && pwd)"
PROJECT_NAME="$(basename "$PROJECT_ROOT")"
PROJECT_SLUG="$(printf '%s' "$PROJECT_NAME" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//')"
cd "$PROJECT_ROOT"

ensure_link() {
  local target="$1"
  local link="$2"
  if [ -L "$link" ]; then
    echo "OK: $link is linked"
  elif [ -e "$link" ]; then
    echo "MISSING SETUP: $link exists but is not the required symlink" >&2
    return 1
  else
    ln -s "$target" "$link"
    echo "CREATED: $link -> $target"
  fi
}

install_generator_plist() {
  if [ "$(uname -s)" != "Darwin" ]; then
    echo "SKIP: launchd generator plist is macOS-only"
    return 0
  fi
  if [ -z "$PROJECT_SLUG" ]; then
    echo "FAIL: could not derive a safe project name for the launchd plist" >&2
    return 1
  fi
  local launch_agents_dir="$HOME/Library/LaunchAgents"
  local plist_path="$launch_agents_dir/com.ios.${PROJECT_SLUG}.harness-generator.plist"
  local template="$HARNESS_ROOT/harness/scripts/com.ios.harness-generator.plist.template"
  if [ ! -f "$template" ]; then
    template="$HARNESS_ROOT/harness/scripts/com.android.harness-generator.plist.template"
  fi
  mkdir -p "$launch_agents_dir"
  sed \
    -e "s|__PROJECT_ROOT__|$PROJECT_ROOT|g" \
    -e "s|__HOME__|$HOME|g" \
    -e "s|__PROJECT_SLUG__|$PROJECT_SLUG|g" \
    "$template" \
    > "$plist_path"
  echo "CREATED: $plist_path"
  echo "Load it when ready: launchctl load $plist_path"
}

initialize_project_entrypoints() {
  local failed=0
  ensure_link ".harness/.agents" ".agents" || failed=1
  ensure_link ".harness/harness" "harness" || failed=1

  if [ ! -e "AGENTS.md" ]; then
    cp "$HARNESS_ROOT/AGENTS.md" "AGENTS.md"
    echo "CREATED: AGENTS.md from .harness/AGENTS.md"
  elif [ -s "AGENTS.md" ]; then
    echo "OK: AGENTS.md already exists (kept project-specific version)"
  else
    echo "MISSING SETUP: AGENTS.md is empty" >&2
    failed=1
  fi
  return "$failed"
}

check_project_context() {
  local missing=0
  local required
  for required in \
    "docs/product/product.md" \
    "docs/product/design_system.md"; do
    if [ ! -s "$required" ]; then
      echo "MISSING: $required" >&2
      missing=1
    else
      echo "OK: $required"
    fi
  done

  if [ "$missing" -ne 0 ]; then
    cat >&2 <<'INSTRUCTIONS'

The project documentation baseline is incomplete. Create these project-owned files:

  1. Create docs/product/product.md with the product capabilities, roadmap, and
     Harness Feature Tracker.
  2. Create docs/product/design_system.md (this is project-owned, not generated by npm).
     It must document the approved SwiftUI tokens, typography, spacing, colors,
     component variants, accessibility constraints, and responsive rules. Use the
     ux-design skill to draft it, then obtain product approval before UI work.

After restoring the files, run:
  bash harness/scripts/init-harness.sh
INSTRUCTIONS
    return 1
  fi

  if [ -e "docs/product/journey-registry.yaml" ]; then
    bash harness/scripts/check-journey-registry.sh --validate
  else
    echo "INFO: docs/product/journey-registry.yaml is not needed until a production journey is declared"
  fi
}

echo "Setting up project entry points..."
initialize_project_entrypoints || {
  echo "FAIL: resolve the reported entry-point conflict, then rerun $0" >&2
  exit 1
}
echo "Checking required project context..."
check_project_context
echo "Creating project-named launchd generator plist..."
install_generator_plist

echo "Validating harness lifecycle and source rules..."
bash harness/scripts/check-feature-lifecycle.sh
bash harness/scripts/check-full-source-rules.sh
echo "Harness initialization complete."
